# Generated by Django 2.0.4 on 2018-05-26 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('botify', '0002_auto_20180421_0924'),
    ]

    operations = [
        migrations.CreateModel(
            name='DOMElementEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CR', 'Create'), ('UP', 'Update'), ('DE', 'Delete')], default='CR', max_length=2)),
                ('path', models.TextField()),
                ('attributes', models.TextField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botify.Session')),
            ],
        ),
    ]
